version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/node:16.15.1
    working_directory: /tmp/dbuzz-client

orbs:
  discord: antonioned/discord@0.1.0

commands:
  common-steps:
    steps:
      - checkout
      - run: yarn install

jobs:
  prod_build_test:
      executor: docker-executor
      steps:
        - common-steps
        - run: yarn run lint
        - discord/status:
            success_message: test build success on mainnet branch
            failure_message: test build failed on mainnet branch
            webhook: https://discord.com/api/webhooks/1146958529668841612/fHV0f_FI-oWw6hFriNcOvlPyyMBdYCMRdvn0eTMX00wgbvg5dvvjhtS1xJdeOIQoEg-x

  dev_build_test:
      executor: docker-executor
      steps:
        - common-steps
        - run: yarn run lint
        - discord/status:
            success_message: test build success on non mainnet branch
            failure_message: test build failed on non mainnet branch
            webhook: https://discord.com/api/webhooks/1146958529668841612/fHV0f_FI-oWw6hFriNcOvlPyyMBdYCMRdvn0eTMX00wgbvg5dvvjhtS1xJdeOIQoEg-x

workflows:
  environment_builds:
    jobs:
      - dev_build_test:
          filters:
            branches:
              ignore: mainnet
      - prod_build_test:
          filters:
            branches:
              only: mainnet