

jobs:
  test_build_prod:
      docker:
        - image: node:14.7.0
      working_directory: /tmp/dbuzz-client
      steps:
        - checkout
        - run: npm install
        - run: npm run lint
        - run: npm run build:prod
        - send_status:
            webhook: https://discordapp.com/api/webhooks/747082285828014170/6TLGC1_wgAAT91n5s3PYZxC9n2_Tj5BzqHQo2tO9miZxnVGKWusD3YA-pO2GjVvOWzuF
      filters:
        branches:
          only: master

  test_build_dev:
      docker:
        - image: node:14.7.0
      working_directory: /tmp/dbuzz-client
      steps:
        - checkout
        - run: npm install
        - run: npm run lint
        - run: npm run build:dev
        - send_status:
            webhook: https://discordapp.com/api/webhooks/747082285828014170/6TLGC1_wgAAT91n5s3PYZxC9n2_Tj5BzqHQo2tO9miZxnVGKWusD3YA-pO2GjVvOWzuF
      filters:
        branches:
          ignore: master


workflows:
  version: 2
  orbs:
    discord: antonioned/discord@0.1.0
  commands:
    send_status: discord/status
  environment_builds:
    jobs:
    - test_build_dev
    - test_build_prod
