version: 2.1
orbs:
  discord: antonioned/discord@0.1.0
commands:
  send_status: discord/status

jobs:
  test-build-prod:
    steps:
      - run: npm run build:prod
    filters:
      branches:
        only: master
  test-build-dev:
    steps:
      - run: npm run build:dev
    filters:
      branches:
        ignore: master


jobs:
  build:
    docker:
      - image: node:14.7.0
    working_directory: /tmp/dbuzz-client
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - test-build-prod
      - test-build-dev
      - send_status:
          webhook: https://discordapp.com/api/webhooks/747082285828014170/6TLGC1_wgAAT91n5s3PYZxC9n2_Tj5BzqHQo2tO9miZxnVGKWusD3YA-pO2GjVvOWzuF
