version: 2
notify:
  webhooks:
    - url: https://discordapp.com/api/webhooks/747082285828014170/6TLGC1_wgAAT91n5s3PYZxC9n2_Tj5BzqHQo2tO9miZxnVGKWusD3YA-pO2GjVvOWzuF
jobs:
  build:
    docker:
      - image: node:14.7.0
    working_directory: /tmp/dbuzz-client
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - notify



