version: 2.1

executors:
  docker-executor:
    docker:
      - image: node:14.18.1
    working_directory: /tmp/dbuzz-client

orbs:
  discord: antonioned/discord@0.1.0

commands:
  common-steps:
    steps:
      - checkout
      - run: npm install
      - run: npm run lint

jobs:
  prod_build_test:
      executor: docker-executor
      steps:
        - common-steps
        - run: npm run build:prod
        - discord/status:
            success_message: test build success on mainnet branch
            failure_message: test build failed on mainnet branch
            webhook: https://discordapp.com/api/webhooks/747082285828014170/6TLGC1_wgAAT91n5s3PYZxC9n2_Tj5BzqHQo2tO9miZxnVGKWusD3YA-pO2GjVvOWzuF

  dev_build_test:
      executor: docker-executor
      steps:
        - common-steps
        - run: npm run build:dev
        - discord/status:
            success_message: test build success on non mainnet branch
            failure_message: test build failed on non mainnet branch
            webhook: https://discordapp.com/api/webhooks/747082285828014170/6TLGC1_wgAAT91n5s3PYZxC9n2_Tj5BzqHQo2tO9miZxnVGKWusD3YA-pO2GjVvOWzuF

workflows:
  environment_builds:
    jobs:
      - dev_build_test:
          filters:
            branches:
              ignore: mainnet
      - prod_build_test:
          filters:
            branches:
              only: mainnet
